### ISSUE TITLE
Territory Gained Displays Wrong Metrics

### ISSUE THREAD

**Issue by j-clap** [twosigma/Halite-II#918]
Territory gained seems to display a value exceeding 200, despite the fact that planets are capped at (4 + 4*player_count).

e.g.: http://35.185.45.87/play/?game_id=1804246&replay_class=0&replay_name=replay-20171022-160403%2B0000--3645488260-264-176-1508688217

**Comment by harikmenon** [comment]
removed this for now, will add it back if users needs it
