### ISSUE TITLE
Halite game engine does not build on mac

### ISSUE THREAD

**Issue by harikmenon** [twosigma/Halite-II#927]
Whatever change we make, we should try to qualify that under OS=Mac to prevent breaks in other oses

-- Build files have been written to: /Users/harikrishnamenon/HaliteCode/Halite-II/environment
Harikrishnas-MacBook-Pro:environment harikrishnamenon$ make -j2
[  4%] Building CXX object CMakeFiles/halite.dir/core/Constants.cpp.o
[  4%] Building CXX object CMakeFiles/halite.dir/core/Entity.cpp.o
[  9%] Building CXX object CMakeFiles/halite.dir/core/GameEvent.cpp.o
[  9%] Building CXX object CMakeFiles/halite.dir/core/Halite.cpp.o
[ 12%] Building CXX object CMakeFiles/halite.dir/core/Replay.cpp.o
[ 14%] Building CXX object CMakeFiles/halite.dir/core/SimulationEvent.cpp.o
[ 17%] Building CXX object CMakeFiles/halite.dir/core/Statistics.cpp.o
[ 19%] Building CXX object CMakeFiles/halite.dir/core/hlt.cpp.o
[ 21%] Building CXX object CMakeFiles/halite.dir/core/mapgen/AsteroidCluster.cpp.o
[ 24%] Building CXX object CMakeFiles/halite.dir/core/mapgen/Generator.cpp.o
[ 26%] Building CXX object CMakeFiles/halite.dir/core/mapgen/SolarSystem.cpp.o
[ 29%] Building CXX object CMakeFiles/halite.dir/networking/BotInputError.cpp.o
[ 31%] Building CXX object CMakeFiles/halite.dir/networking/Networking.cpp.o
[ 34%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/common/entropy_common.c.o
[ 36%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/common/error_private.c.o
[ 39%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/common/fse_decompress.c.o
[ 41%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/common/pool.c.o
[ 43%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/common/threading.c.o
[ 46%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/common/xxhash.c.o
/Users/harikrishnamenon/HaliteCode/Halite-II/environment/networking/Networking.cpp:434:11: warning: unused variable 'ppid_before_fork'
      [-Wunused-variable]
    pid_t ppid_before_fork = getpid();
          ^
[ 48%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/common/zstd_common.c.o
[ 51%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/compress/fse_compress.c.o
[ 53%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/compress/huf_compress.c.o
[ 56%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/compress/zstd_compress.c.o
[ 58%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/compress/zstdmt_compress.c.o
[ 60%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/decompress/huf_decompress.c.o
[ 63%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/decompress/zstd_decompress.c.o
[ 65%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/deprecated/zbuff_common.c.o
[ 68%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/deprecated/zbuff_compress.c.o
[ 70%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/deprecated/zbuff_decompress.c.o
[ 73%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/dictBuilder/cover.c.o
[ 75%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/dictBuilder/divsufsort.c.o
[ 78%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/dictBuilder/zdict.c.o
[ 80%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/legacy/zstd_v01.c.o
[ 82%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/legacy/zstd_v02.c.o
[ 85%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/legacy/zstd_v03.c.o
[ 87%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/legacy/zstd_v04.c.o
[ 90%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/legacy/zstd_v05.c.o
[ 92%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/legacy/zstd_v06.c.o
[ 95%] Building C object CMakeFiles/halite.dir/zstd-1.3.0/lib/legacy/zstd_v07.c.o
[ 97%] Building CXX object CMakeFiles/halite.dir/main.cpp.o
1 warning generated.
[100%] Linking CXX executable halite
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [halite] Error 1
make[1]: *** [CMakeFiles/halite.dir/all] Error 2
make: *** [all] Error 2
Harikrishnas-MacBook-Pro:environment harikrishnamenon$

**Comment by lidavidm** [comment]
Looks like we can't make static binaries on OSX:
https://stackoverflow.com/questions/5259249/creating-static-mac-os-x-c-build

**Comment by harikmenon** [comment]
One of these look to be the culprit. Any short term changes we can do to build this on the mac locally so we can publish binaries?

ecb4f3c24cb81b55d5fb7170dfdb52139ecd268f, 451f785aed6f8d1f40749e983b1c01d77669d0b0, 881d91ebfd8d302f2b780fb8bd6cf27cf5878116

**Comment by lidavidm** [comment]
On OSX, I would remove `-static`.

**Comment by lidavidm** [comment]
@harikmenon Try the fix-osx branch I just pushed.

**Comment by Snaar** [comment]
I took liberty of adding the link to that stackoverflow to the CMakeList as comment.

**Comment by Snaar** [comment]
Checked it on macbook just now - works good. Went ahead and merged into master via #930
