### ISSUE TITLE
redirect all http to https on our website images

### ISSUE THREAD

**Issue by harikmenon** [twosigma/Halite-II#931]
David: We are having issues with our website images, our website keeps switching between http and https, can you take a look at it and see if we can fix it in the image in the nginix config itself

**Comment by lidavidm** [comment]
I'm rebuilding an image with this added to the nginx config:

```
        if ($http_x_forwarded_proto = "http") {
                rewrite  ^/(.*)$  https://halite.io/$1 permanent;
        }
```

We aren't doing HTTPS ourselves - we're doing it through the load balancer - so what this does is check the header that the load balancer adds, specifying whether the original request was HTTP or HTTPS, and if it was HTTP, then we redirect to HTTPS.

**Comment by harikmenon** [comment]
Okay sweet. The website image is something xii

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lidavidm** [comment]
I just made the new image, `website-image-xiii`, and deprecated the old one. You should be able to recreate the instances with the new image.

**Comment by harikmenon** [comment]
okay doing it now

**Comment by harikmenon** [comment]
no changes to the loadbalancer defintion right?

**Comment by harikmenon** [comment]
I'm building a new instance tempalte now

**Comment by lidavidm** [comment]
No changes to the load balancer, this is all on nginx's side.

**Comment by lidavidm** [comment]
@harikmenon seems like it's working now?

**Comment by harikmenon** [comment]
Yes, thanks dude, As always you are a lifesaver

**Comment by harikmenon** [comment]
there might be a few issues we can use your help with. talking to a user. Give me a sec
